### ISSUE TITLE
toggler

### ISSUE THREAD

**Issue by kamelot43** [Alexiy1984/core_kit#13]
по этому элементу нет вопросов.

единственное можно пару цветов прикрутить.

**Comment by Alexiy1984** [comment]
Добавил новые стили для переключателя + переписал скрипт
![toggler](https://user-images.githubusercontent.com/31098105/99511664-9e72f080-2999-11eb-8bb3-9dc88f66ff4e.gif)

**Comment by kamelot43** [comment]
fixed
