### ISSUE TITLE
Заметка 

### ISSUE THREAD

**Issue by kamelot43** [Alexiy1984/core_kit#2]
https://github.com/Alexiy1984/core_kit/blob/c090b754123cf41936e7d4b445e042f6db4d2712/scss/button.scss#L27-L38

Одна из идей, которую можно пока протестировать по миксинам.

//миксин для задания фоновых цветов для кнопки (normal, hover, active, focus)
//принимает массив цветов (4 цвета) для каждого состояния и привязывает к состоянию hover  и active и т.д.

//миксин для закрашивания цвета иконки внутри кнопки ( если это необходимо)
//по-умолчанию принимаем, что цвет иконки меняется на белый. это можно прописать в css. сам миксин может переопределить это поведение.

//внутри кнопки danger или любой другой задаем цвет шрифта + используем миксин для задания фоновых цветов,
// если возникает задача поменять цвет иконки дополнительно используем миксин для заливки цветов.
//основной посыл - упростить миксины . разбить на два простых и отдельных миксина : только задание фонового цвета и миксин для закрашивания иконки , если это необходимо.

//по идее должно сократить количество шагов при объявлении новой кнопки.

**Comment by Alexiy1984** [comment]
Переработал миксин и перенес переменные с цветами кнопок в _variables.scss. Необходимо применить его еще для одного элемента
