### ISSUE TITLE
Рамки 

### ISSUE THREAD

**Issue by kamelot43** [Alexiy1984/core_kit#4]
Слева от кнопки рамки нет вокруг кнопки 
Справа от кнопки рамка есть вокруг кнопки 

<img width="1391" alt="Снимок экрана 2020-11-06 в 11 42 25" src="https://user-images.githubusercontent.com/20759127/98345154-5234c180-2025-11eb-93d6-8ca507a655ba.png">

<img width="1353" alt="Снимок экрана 2020-11-06 в 11 42 32" src="https://user-images.githubusercontent.com/20759127/98345161-54971b80-2025-11eb-88b7-547e1d704232.png">

**Comment by Alexiy1984** [comment]
Рамка поправлена.
