### ISSUE TITLE
Состояние active для кнопок

### ISSUE THREAD

**Issue by kamelot43** [Alexiy1984/core_kit#5]
<img width="1439" alt="Screenshot at Nov 10 10-26-50" src="https://user-images.githubusercontent.com/20759127/98643074-81a63f80-233f-11eb-93ff-447ac33f74dc.png">

элемент primary объявлен дважды. возможно просто опечатка.
и для других кнопок нужно будет прописать состояние active по аналогии с кнопкой primary.

**Comment by kamelot43** [comment]
<img width="1437" alt="Screenshot at Nov 10 10-32-20" src="https://user-images.githubusercontent.com/20759127/98643802-9505da80-2340-11eb-9424-635bad8411c7.png">


При передаче параметров в миксин некоторые значения дублируются и передаются дважды.
Например в normal_colors : второй и третий параметр. Можно попробовать значения записать в переменную и как-то ее использовать или использовать значение по-умолчанию ? идея в том, чтобы передавать только два параметра.

И в hover_colors . мы всегда вторым параметром передаем rgba(0,0,0,0). можно установить это значение по-умолчанию, чтобы в hover_colors передавать два параметра , а не три.

**Comment by Alexiy1984** [comment]
Убрано лишний сет цветов для primary button
