### ISSUE TITLE
Кнопки 

### ISSUE THREAD

**Issue by kamelot43** [Alexiy1984/core_kit#6]
<img width="1436" alt="Screenshot at Nov 10 10-42-02" src="https://user-images.githubusercontent.com/20759127/98644484-9388e200-2341-11eb-8eb1-5d80601469f4.png">

Вроде текст немного съехал и не по центру сейчас.

**Comment by kamelot43** [comment]
<img width="1249" alt="Снимок экрана 2020-11-10 в 10 41 02" src="https://user-images.githubusercontent.com/20759127/98644534-ab606600-2341-11eb-8900-bcc67aabc51c.png">

серая рамка на кнопке при ховере. серая рамка по идее не должна быть со стороны цветной кнопки.

**Comment by kamelot43** [comment]
<img width="1439" alt="Screenshot at Nov 10 10-42-48" src="https://user-images.githubusercontent.com/20759127/98644641-d77be700-2341-11eb-9a98-15e307b7f054.png">

разная толщина линий в блоке с кнопками. нужно понять почему там.

**Comment by kamelot43** [comment]
<img width="266" alt="Снимок экрана 2020-11-10 в 10 43 14" src="https://user-images.githubusercontent.com/20759127/98644689-ecf11100-2341-11eb-98b6-3ca283c9b8cb.png">

вроде цвет иконки меняется сразу без анимации. цвет рамки меняется плавно.

**Comment by kamelot43** [comment]
<img width="1435" alt="Screenshot at Nov 10 10-48-09" src="https://user-images.githubusercontent.com/20759127/98644915-3d686e80-2342-11eb-9ea9-c92f6d4fe7f8.png">

кнопка danger "прыгает" при ховере. primary работает нормально.

**Comment by kamelot43** [comment]
<img width="672" alt="Screenshot at Nov 10 11-30-02" src="https://user-images.githubusercontent.com/20759127/98649112-41978a80-2348-11eb-8d4f-82407557ecf5.png">

не хватает одной кнопки

**Comment by Alexiy1984** [comment]
Добавлена анимация выделения для кнопок
Убраны "прыжки" кнопки
 Границы выделенной кнопки перемещены на первый план

**Comment by Alexiy1984** [comment]
Добавлена круглая кнопка
![Nov-18-2020 10-15-55](https://user-images.githubusercontent.com/31098105/99497628-416e3f00-2987-11eb-9641-3281b46949d7.gif)

**Comment by kamelot43** [comment]
fixed
