### ISSUE TITLE
Инпуты 

### ISSUE THREAD

**Issue by kamelot43** [Alexiy1984/core_kit#7]
<img width="1439" alt="Screenshot at Nov 10 10-51-34" src="https://user-images.githubusercontent.com/20759127/98645257-c2538800-2342-11eb-96b4-b625079d2302.png">

разная толщина рамок 
//
нужно протестировать вариант с append и prepend (ширина рамок)

**Comment by kamelot43** [comment]
<img width="1439" alt="Screenshot at Nov 10 10-52-56" src="https://user-images.githubusercontent.com/20759127/98645377-e9aa5500-2342-11eb-906c-c2e1c0cdda58.png">

этот момент стоит уточнить у Бахи или Веталика. Как должно выглядеть поле при фокусе ? такой вариант с outline мне кажется не очень красивым. как поступить - лучше спросить у ребят кто шарит в дизайне )

**Comment by kamelot43** [comment]
цвет иконок должен менять плавно, а не мгновенно.
Нужно еще предусмотреть вариант поля c label и протестировать как все работает.
Возможно сейчас в макете нет label, но это очень частый кейс и его стоит предусмотреть . 

вот кстати нашел label 

<img width="1439" alt="Screenshot at Nov 10 11-14-46" src="https://user-images.githubusercontent.com/20759127/98647490-faa89580-2345-11eb-9d82-c77e80142caf.png">

**Comment by kamelot43** [comment]
<img width="746" alt="Screenshot at Nov 10 10-56-12" src="https://user-images.githubusercontent.com/20759127/98645681-5faebc00-2343-11eb-8d83-29dcf1b89b10.png">

нужно понять дальнейшую логику работы этих кнопок. этот вопрос тоже стоит уточнить у Бахи. при клике на глаз мы показываем/скрываем текст или что должно быть ? нужно будет для теста запилить пару обработчиков 

.......................
скорее всего реализация должна быть такой:
в полях, где есть глазик - клик по нему скрывает/показывает текст в поле.

<img width="1439" alt="Screenshot at Nov 10 11-18-35" src="https://user-images.githubusercontent.com/20759127/98647901-9e924100-2346-11eb-833d-6cd01e345519.png">

**Comment by kamelot43** [comment]
<img width="1432" alt="Screenshot at Nov 10 10-58-56" src="https://user-images.githubusercontent.com/20759127/98645969-c0d68f80-2343-11eb-8f61-af81c4b6b405.png">

при фокусе в поле placeholder должен плавно исчезать.

**Comment by kamelot43** [comment]
<img width="1439" alt="Screenshot at Nov 10 11-06-51" src="https://user-images.githubusercontent.com/20759127/98646739-da2c0b80-2344-11eb-96a1-92a2e42e136e.png">

цвет рамок

**Comment by kamelot43** [comment]
<img width="1439" alt="Screenshot at Nov 10 11-06-11" src="https://user-images.githubusercontent.com/20759127/98646869-12cbe500-2345-11eb-9642-422b71a2c61f.png">

вот это поле сложное. оно должно принимать три значение : номер карты (числовой формат). есть ограничения по макс длине символов + разбиваем на группы (4 * 4 символа) (можно посмотреть валидацию с помощью регялярных выражений).

далее принимаем срок действия карты + CVV2/CVC2 (все значения числовые). скорее всего в bootstrap нет похожего кейса и придется искать стороннее решение (библиотеку какую-нибудь).

сейчас это поле не корректно работает. 
<img width="1429" alt="Screenshot at Nov 10 11-07-58" src="https://user-images.githubusercontent.com/20759127/98647312-bb7a4480-2345-11eb-8c56-1219d7d97a23.png">

левая часть не заполняется , в поле для карты принимает текст , чего в принципе быть не может

**Comment by kamelot43** [comment]
<img width="745" alt="Screenshot at Nov 10 11-21-03" src="https://user-images.githubusercontent.com/20759127/98648092-db5e3800-2346-11eb-83a9-3af4ad411cbf.png">

не все варианты инпутов сейчас реализованы 

//
обсудить с Деном или Бахой  как должно работать поле с тегами и какой у него мин. функционал.

**Comment by kamelot43** [comment]
<img width="1439" alt="Screenshot at Nov 10 11-23-45" src="https://user-images.githubusercontent.com/20759127/98648351-36902a80-2347-11eb-9848-542311319996.png">

в одном случае ховера нет, в другом - резкий без анимации

**Comment by Alexiy1984** [comment]
![input-group placeholder](https://user-images.githubusercontent.com/31098105/100055778-72da8500-2e35-11eb-88e5-6c63366b279b.gif)

**Comment by kamelot43** [comment]
где-то анимация плавная , где-то мгновенная. (страница components и main)
<img width="1439" alt="Screenshot at Nov 24 10-58-56" src="https://user-images.githubusercontent.com/20759127/100064963-3cf0cd00-2e44-11eb-9588-17e2ea864592.png">

<img width="1439" alt="Screenshot at Nov 24 10-58-33" src="https://user-images.githubusercontent.com/20759127/100064981-437f4480-2e44-11eb-84f1-690148a63740.png">

**Comment by kamelot43** [comment]
<img width="1426" alt="Screenshot at Nov 24 10-42-18" src="https://user-images.githubusercontent.com/20759127/100065028-54c85100-2e44-11eb-82cb-69d4a91e72a4.png">

вот эти поля для карты сейчас не работают. можно ввести текст и нет возможности ввести все данные картты. другие поля работают нормально

**Comment by kamelot43** [comment]
<img width="628" alt="Снимок экрана 2020-11-24 в 11 03 31" src="https://user-images.githubusercontent.com/20759127/100065335-b8eb1500-2e44-11eb-8b51-6ad7c3d9a428.png">

<img width="648" alt="Снимок экрана 2020-11-24 в 11 03 21" src="https://user-images.githubusercontent.com/20759127/100065353-bd173280-2e44-11eb-8cb3-414a83d81cca.png">

при ховере кнопка становится светлее, а рамка у поля темнее. виден контраст . это конечно не супер страшно, но разница визуально видна.

**Comment by kamelot43** [comment]
<img width="1439" alt="Screenshot at Nov 24 11-12-46" src="https://user-images.githubusercontent.com/20759127/100066385-16cc2c80-2e46-11eb-824e-394454843335.png">

<img width="1439" alt="Screenshot at Nov 24 11-13-22" src="https://user-images.githubusercontent.com/20759127/100066413-1fbcfe00-2e46-11eb-8340-df18a4efdbfc.png">

похоже, что  у нас есть два элемента, которые дублируют друг друга. form-group не переиспользует компонент form . в теории можно на form-group применить стили form. вроде мы обсуждали этот момент. с одной стороны не хочется оборачивать input лишними тегами, с другой стороны получается дублирование элементов с похожим функционалом. возникнет вопрос что использовать.

**Comment by Alexiy1984** [comment]
![input group number](https://user-images.githubusercontent.com/31098105/100104103-d042f600-2e76-11eb-983e-bc5570167399.gif)

у этого элемента  должны быть три атрибута:  минимальное значение, максимальное значение. . например значение 0 минимальное. в -1 при таком варианте не получится уйти.  

///

спорные моменты по dropdown и input number обсуди пожалуйста с Деном. как должно работать и какой мин. функционал должен быть предусмотрен .

**Comment by kamelot43** [comment]
<img width="1439" alt="Screenshot at Nov 25 10-50-05" src="https://user-images.githubusercontent.com/20759127/100197943-29109e00-2f0c-11eb-8037-d2c73d7171e2.png">

в поле для ввода карты не активно поля для периода действия карты

**Comment by kamelot43** [comment]
<img width="1432" alt="Screenshot at Nov 25 10-52-46" src="https://user-images.githubusercontent.com/20759127/100198076-64ab6800-2f0c-11eb-8317-15faad96a783.png">

не совсем понимаю как должны работать эти поля. это вариант append и prepend без рамок ?

**Comment by kamelot43** [comment]
при вводе текста в поле синяя обводка должна появляться плавно и плавно исчезать при перемещении фокуса .
и нужно протестить как будет работать с цветными полями и иконками , которые вроде были .

если поля цветные - то и обводка цветная должна быть. синий цвет скорее всего привязан к дефолтному полю.
если это спорный вопрос - стоит обсудить с дизайнерами.

**Comment by Alexiy1984** [comment]
> при вводе текста в поле синяя обводка должна появляться плавно и плавно исчезать при перемещении фокуса .
> и нужно протестить как будет работать с цветными полями и иконками , которые вроде были .
> 
> если поля цветные - то и обводка цветная должна быть. синий цвет скорее всего привязан к дефолтному полю.
> если это спорный вопрос - стоит обсудить с дизайнерами.

Input group состоит из нескольких элементов и анимация обводки выглядит некрасиво

**Comment by Alexiy1984** [comment]
> <img alt="Screenshot at Nov 10 10-51-34" width="1439" src="https://user-images.githubusercontent.com/20759127/98645257-c2538800-2342-11eb-96b4-b625079d2302.png">
> 
> разная толщина рамок
> //
> нужно протестировать вариант с append и prepend (ширина рамок)

Исправлено

**Comment by Alexiy1984** [comment]
> ![input group number](https://user-images.githubusercontent.com/31098105/100104103-d042f600-2e76-11eb-983e-bc5570167399.gif)
> 
> у этого элемента должны быть три атрибута: минимальное значение, максимальное значение. . например значение 0 минимальное. в -1 при таком варианте не получится уйти.
> 
> ///
> 
> спорные моменты по dropdown и input number обсуди пожалуйста с Деном. как должно работать и какой мин. функционал должен быть предусмотрен .

Обсудили с Денисом оставляем как есть сейчас

**Comment by kamelot43** [comment]
fixed
