### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by kamelot43** [Alexiy1984/core_kit#8]
<img width="670" alt="Screenshot at Nov 12 16-02-32" src="https://user-images.githubusercontent.com/20759127/98943561-c0372800-2500-11eb-9a0b-d8a98926e661.png">

<img width="1351" alt="Screenshot at Nov 12 16-02-54" src="https://user-images.githubusercontent.com/20759127/98943565-c1685500-2500-11eb-9b80-607958c0e9b5.png">

в пагинации нужно предусмотреть варианты, для различный цветов кнопки. сейчас в макете определены три цвета.

/// fixed

**Comment by kamelot43** [comment]
<img width="563" alt="Снимок экрана 2020-11-12 в 16 05 58" src="https://user-images.githubusercontent.com/20759127/98943741-02606980-2501-11eb-910b-d19edeefa77c.png">

активный пункт имеет большую высоту, чем пункт, на который навели курсор. анимация смены цвета должна быть плавной

**Comment by kamelot43** [comment]
кнопки имеют разные пропорции. нужно привязать к одному размеру.
при смене активной кнопки сильно заметны разные пропорции кнопок.

<img width="1410" alt="Снимок экрана 2020-11-12 в 16 08 06" src="https://user-images.githubusercontent.com/20759127/98944015-6f73ff00-2501-11eb-8e48-906d8e45995e.png">

<img width="1440" alt="Снимок экрана 2020-11-12 в 16 08 17" src="https://user-images.githubusercontent.com/20759127/98944023-73a01c80-2501-11eb-86fc-a00d2cbfc13c.png">

<img width="1431" alt="Снимок экрана 2020-11-12 в 16 08 33" src="https://user-images.githubusercontent.com/20759127/98944033-7733a380-2501-11eb-98a3-6e87b5e22c12.png">


///
нужно понять какими должны быть пропорции кнопок - привязаны к одному размеру или допустимо оставить так, как есть сейчас
спорные вопросы по пагинации и работе других элементов можно обсудить с Деном или Бахой.

**Comment by kamelot43** [comment]
<img width="930" alt="Screenshot at Nov 12 16-10-22" src="https://user-images.githubusercontent.com/20759127/98944107-95010880-2501-11eb-9410-566f52b1a865.png">

при пролистывании прыгает пагинация

**Comment by kamelot43** [comment]
<img width="1398" alt="Screenshot at Nov 12 16-14-03" src="https://user-images.githubusercontent.com/20759127/98944638-633c7180-2502-11eb-8e9e-8594f2fa564e.png">

нужно понять как должна работать пагинация при достижении предпоследнего элемента. нужно показывать точки или нет ? сами точки должны быть кликабельными ? 

//// нужно понять как должны работать точки

**Comment by kamelot43** [comment]
<img width="1389" alt="Screenshot at Nov 12 16-20-47" src="https://user-images.githubusercontent.com/20759127/98945136-23c25500-2503-11eb-9812-e65372ebc47e.png">
по идее при достижении крайних значений стрелки должны становиться неактивными , как-то менять свой цвет, чтобы было понятно, что по ним нельзя кликать.

///
сейчас при достижении крайних значений стрелки активны. должен быть серый фон или что-то типо того

**Comment by Alexiy1984** [comment]
![pagination counter](https://user-images.githubusercontent.com/31098105/100055467-f34cb600-2e34-11eb-9817-38cf98dbce3a.gif)

**Comment by Alexiy1984** [comment]
![pagination colors](https://user-images.githubusercontent.com/31098105/100076332-26ea0900-2e52-11eb-9469-1047b97bb59a.gif)
